services:
  mongo:
    image: mongo:8.2
    container_name: coralsync_db
    ports:
      - "27017:27017"
    volumes:
      - coralsync_mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=fDRbswIC

volumes:
  coralsync_mongo_data: